---
apiVersion: v1
kind: Secret
metadata:
  name: onthebuns-auto-campaigns
data:
  ONTHATASS_EMAIL: base64-encoded-email
  ONTHATASS_PASSWORD: base64-encoded-password
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: onthebuns-auto-campaigns
spec:
  schedule: '0 12 15 * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: onthebuns-auto-campaigns
              image: ghcr.io/jamezrin/onthebuns-auto-campaigns:latest
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: onthebuns-auto-campaigns
          imagePullSecrets:
            - name: ghcr-registry
          restartPolicy: OnFailure
